image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy

build web:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master  
  tags:
    - docker

deploy prod:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  when: manual
  script:
    - kubectl apply -f k8s/ -n humanz-blog
  tags:
    - k8s  